name: Sonar Cloud | Analysis Static Code

on:
  push:
    branches:
      - main    
      - development
      - staging
  workflow_dispatch:

jobs:
  staticcodeanalysis:    
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17 for Static Analysis
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x.x
    - name: Install Sonar Scanner
      shell: pwsh
      run: |
        New-Item -Path ./.sonar/scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build And Test
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"OtavioVB_OVB.Demos.Eschody" /o:"otaviovb-1" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.coverage.exclusions="/tst/**/*,benchs/**,migrations/**" /d:sonar.exclusions="/tst/**/*,benchs/**,migrations/**"
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="Coverage/" ./tst/OVB.Demos.Eschody.UnitTests/OVB.Demos.Eschody.UnitTests.csproj
        ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"